### ISSUE TITLE
Role-based security

### ISSUE THREAD

**Issue by asclines** [TTUSDC/CPCEEDWebApp#23]
As of now, there is no role based security for the Firebase app. Not that it is important yet due this only being in development, but I'm creating this issue to publicly remind myself to add role-based security on the Firebase side in the future.

**Comment by StephanieKeck** [comment]
I was wondering if it would be better to implement an activities-based permissions system (ex 'canCreateEvents') instead of, or in addition to, a role-based system. In such a system permissions-aware components would not need to be aware of roles but would define a list of permissions they require based on their function (i.e. a create event module would require the 'canCreateEvents' permission). In my mind this would be cleaner and more flexible long term. Coordinators would still see users as having roles, but the act of assigning new roles to users would actually be changing their permissions on the backend. This system would allow us to create features where coordinators could assign additional permissions to specific users, or create new roles altogether, very easily. We would also not have to change every permissions-aware component in our application whenever we decide to add a new user role.

**Comment by asclines** [comment]
@StephanieKeck That makes perfect sense for the client side app. However, I still think role-based security for the Firebase is the right way to go. This is for managing who can read/write from various parts of the database. i.e. you can only modify a user object if you are that user or an admin.

**Comment by NilsG-S** [comment]
While the idea does sound interesting, I'm concerned about getting bogged down at this juncture. I think it's more important to get a functional product out quickly than to make it absolutely perfect the first time. If necessary, we can do as @asclines says and simply decide what activities-based permissions to assign to the client at authentication time based on user type.

**Comment by asclines** [comment]
True, but we should add some security protocols in the client lest we forget to later. Again, to emphasize what the issue says in it's description, the role-based security part at least should be held off till later.

**Comment by NilsG-S** [comment]
Sorry, I'm not sure I understand. Do you mean that we should have code on the client side that only loads components that the current user is allowed to see?

**Comment by asclines** [comment]
I wasn't being too specific. Just trying to make it clear that security on the server and security on the client are two different problems we need to tackle and while we aren't handling Firebase security yet, there should still be some security on the client side. How that's handled is up to y'all.

**Comment by NilsG-S** [comment]
The code I just merged into master has a higher order component that checks whether a user is authenticated before allowing pages to load. Is that kind of what you had in mind?

**Comment by asclines** [comment]
Yes, that will be sufficient for now at least.

**Comment by StephanieKeck** [comment]
@NilsG-S I agree about automatically assigning permissions for now. I was thinking it would be easy to add a permissions field to /users objects which would just be a simple array. Is there a reason we have different user object types rather than a single /user object type with a 'role' field?

**Comment by NilsG-S** [comment]
@StephanieKeck 
I believe the current database only has one `user` object type. Each instance of the object has a role field that specifies the type of user they are.

**Comment by StephanieKeck** [comment]
@NilsG-S Okay, I was getting confused by the App Data document.

**Comment by asclines** [comment]
@NilsG-S that is correct.

**Comment by asclines** [comment]
Closing because we are no longer using Firebase see [here](https://github.com/TTUSDC/CPCEEDWebAppBackend/issues/7)
